name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t jupyterlab-image:latest .

      - name: Display Access Information
        run: |
          echo "---------------------------------------------------"
          echo "JupyterLab Build Successful!"
          echo "Access URL: http://localhost:7860/lab?token=ab87036181"
          echo "Token: ab87036181"
          echo "---------------------------------------------------"
